server:
    port: 8190
    servlet:
        context-path: /auth
spring:
    flyway:
        locations: classpath:db/migration
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost/users
        username: postgres
        password: Bb123456789
    jpa:
        show-sql: true

jwt:
    secret: fefdsaf3e3248923hfai
    lifetime: 36000

